"""added email to usre

Revision ID: 853585673b43
Revises: 744eddbe3e2e
Create Date: 2022-03-27 22:58:45.841788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853585673b43'
down_revision = '744eddbe3e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
